Ingest csv review - HYPM
oceanobservatories/ingestion-csvs pull request #408
Opened 2021-05-11 21:36 UTC by cdobs

Completed review of HYPM telemetered and recovered ingestion csvs

2021-05-12 14:22 UTC, snwhite requested changes
1) GA02HYPM D00002, the controller S/N should be 14880, with 00 and 01 after it. I know it doesn't matter since it is commented out, but it would be good to be consistent.
2) We will not be ingesting any telemetered ZPLSG data, so we may want to remove those lines from all of the the D0000x CSVs.

2021-05-12 14:22 UTC, snwhite commented on GI02HYPM/GI02HYPM_R00005_ingest.csv
> +mi.dataset.driver.vel3d_l.wfp.vel3d_l_wfp_recovered_driver,/omc_data/whoi/OMC/GI02HYPM/R00005/instruments/GWFP_sn*/0*/A*.DA?,GI02HYPM-WFP02-05-VEL3DL000,recovered_wfp,Available,
Looks good.

2021-05-12 14:22 UTC, snwhite commented on GI02HYPM/GI02HYPM_R00006_ingest.csv
> +#mi.dataset.driver.WFP_ENG.STC_IMODEM.wfp_eng_stc_imodem_recovered_driver,/omc_data/whoi/OMC/GI02HYPM/R00006/instruments/GWFP_sn*/0*/E*.DA?,GI02HYPM-WFP02-00-WFPENG000,recovered_wfp,Pending,unable to
Looks good.

2021-05-12 14:22 UTC, snwhite commented on GP02HYPM/GP02HYPM_D00007_ingest.csv
> +#mi.dataset.driver.vel3d_l.wfp.sio.vel3d_l_wfp_sio_telemetered_driver,/omc_data/whoi/OMC/GP02HYPM/D00007/*.wa_wfp_1398821.dat,GP02HYPM-WFP02-05-VEL3DL000,telemetered,Available,No mule data from upper
Looks good.

2021-05-12 14:22 UTC, snwhite commented on GP02HYPM/GP02HYPM_R00005_ingest.csv
> +#mi.dataset.driver.vel3d_l.wfp.vel3d_l_wfp_recovered_driver,/omc_data/whoi/OMC/GP02HYPM/R00005/instruments/GWFP_sn12997-01/0*/A*.DA?,GP02HYPM-WFP02-05-VEL3DL000,recovered_wfp,Not Expected,instrument
Looks good.

2021-05-12 14:22 UTC, snwhite commented on GP02HYPM/GP02HYPM_R00006_ingest.csv
> +#mi.dataset.driver.WFP_ENG.STC_IMODEM.wfp_eng_stc_imodem_recovered_driver,/omc_data/whoi/OMC/GP02HYPM/R00006/instruments/GWFP_sn13104-02/0*/E*.DA?,GP02HYPM-WFP02-00-WFPENG000,recovered_wfp,Pending,Ca
Looks good.

2021-05-12 14:22 UTC, snwhite commented on GP02HYPM/GP02HYPM_R00006_ingest.csv
> +#mi.dataset.driver.WFP_ENG.STC_IMODEM.wfp_eng_stc_imodem_recovered_driver,/omc_data/whoi/OMC/GP02HYPM/R00006/instruments/GWFP_sn12936-02/0*/E*.DA?,GP02HYPM-WFP03-00-WFPENG000,recovered_wfp,Pending,Ca
Looks good.

2021-05-12 14:22 UTC, snwhite commented on GS02HYPM/GS02HYPM_R00003_ingest.csv
> +#mi.dataset.driver.WFP_ENG.STC_IMODEM.wfp_eng_stc_imodem_recovered_driver,/omc_data/whoi/OMC/GS02HYPM/R00003/cg_data/MSIOC_sn/WFP/E22*.DA?,GS02HYPM-WFP03-00-WFPENG000,recovered_wfp,Pending,parser nee
Looks good.

2021-05-12 17:08 UTC, snwhite approved these changes
Additional changes look good!

2021-05-12 17:08 UTC, snwhite commented on GA02HYPM/GA02HYPM_D00001_ingest.csv
> -#,,GA02HYPM-MPM01-02-ZPLSGA010,telemetered,Not Deployed,Not installed
Looks good.

2021-05-12 17:08 UTC, snwhite commented on GA02HYPM/GA02HYPM_D00002_ingest.csv
> -#,,GA02HYPM-MPM01-02-ZPLSGA010,telemetered,Not Deployed,Not installed
Looks good.

2021-05-12 17:08 UTC, snwhite commented on GA02HYPM/GA02HYPM_D00002_ingest.csv
> +#mi.dataset.driver.vel3d_l.wfp.sio.vel3d_l_wfp_sio_telemetered_driver,/omc_data/whoi/OMC/GA02HYPM/D00002/*.wa_wfp_1488001.dat,GA02HYPM-WFP03-05-VEL3DL000,telemetered,Not Expected,Data not expected -
Looks good.

2021-05-12 17:08 UTC, snwhite commented on GA02HYPM/GA02HYPM_D00003_ingest.csv
> -#,,GA02HYPM-MPM01-02-ZPLSGA010,telemetered,Pending,Issues with data - MIO investigating
Looks good.

2021-05-12 17:08 UTC, snwhite commented on GI02HYPM/GI02HYPM_D00001_ingest.csv
> -#,,GI02HYPM-MPM01-02-ZPLSGA010,telemetered,Not Deployed,Not deployed
Looks good.

2021-05-12 17:08 UTC, snwhite commented on GI02HYPM/GI02HYPM_D00002_ingest.csv
> -#,,GI02HYPM-MPM01-02-ZPLSGA010,telemetered,Not Deployed,Not Installed
Looks good.

2021-05-12 17:08 UTC, snwhite commented on GI02HYPM/GI02HYPM_D00003_ingest.csv
> -#,/omc_data/whoi/OMC/GI02HYPM/D00003/node23p1.dat ,GI02HYPM-MPM01-02-ZPLSGA010,telemetered,Pending,data present in the master file but not ready for use - no parser available
Looks good.

2021-05-12 17:08 UTC, snwhite commented on GI02HYPM/GI02HYPM_D00004_ingest.csv
> -#,/omc_data/whoi/OMC/GI02HYPM/D00004/node*p1_*.zp*10.dat,GI02HYPM-MPM01-02-ZPLSGA010,telemetered,Pending,no parser
Looks good.

2021-05-12 17:08 UTC, snwhite commented on GI02HYPM/GI02HYPM_D00005_ingest.csv
> -#,/omc_data/whoi/OMC/GI02HYPM/D00005/node*p1_*.zp*10.dat,GI02HYPM-MPM01-02-ZPLSGA010,telemetered,Pending,no parser
Looks good.

2021-05-12 17:08 UTC, snwhite commented on GI02HYPM/GI02HYPM_D00006_ingest.csv
> -#,/omc_data/whoi/OMC/GI02HYPM/D00006/node*p1_*.zp*10.dat,GI02HYPM-MPM01-02-ZPLSGA010,telemetered,Pending,no parser
Looks good.

2021-05-12 17:08 UTC, snwhite commented on GI02HYPM/GI02HYPM_D00007_ingest.csv
> -#,/omc_data/whoi/OMC/GI02HYPM/D00007/node*p1_*.zp*10.dat,GI02HYPM-MPM01-02-ZPLSGA010,telemetered,Pending,no parser
Looks good.

2021-05-12 17:08 UTC, snwhite commented on GP02HYPM/GP02HYPM_D00001_ingest.csv
> -#,,GP02HYPM-MPM01-02-ZPLSGA010,telemetered,Not Deployed,Not deployed
Looks good.

2021-05-12 17:08 UTC, snwhite commented on GP02HYPM/GP02HYPM_D00002_ingest.csv
> -#,,GP02HYPM-MPM01-02-ZPLSGA010,telemetered,Not Deployed,Not deployed
Looks good.

2021-05-12 17:08 UTC, snwhite commented on GP02HYPM/GP02HYPM_D00003_ingest.csv
> -#,,GP02HYPM-MPM01-02-ZPLSGA010,telemetered,Not Deployed,Not deployed
Looks good.

2021-05-12 17:08 UTC, snwhite commented on GP02HYPM/GP02HYPM_D00004_ingest.csv
> -#,,GP02HYPM-MPM01-02-ZPLSGA010,telemetered,Pending,Issues with data -  its in the mdd and nodeXXp1.dat files but MIOs think the data format was corrupted and the system won't be able to read it
Looks good.

2021-05-12 17:08 UTC, snwhite commented on GP02HYPM/GP02HYPM_D00005_ingest.csv
> -#,,GP02HYPM-MPM01-02-ZPLSGA010,telemetered,Not Expected,No telemetered data expected (no gliders deployed)
Looks good.

2021-05-12 17:08 UTC, snwhite commented on GP02HYPM/GP02HYPM_D00006_ingest.csv
> -#,,GP02HYPM-MPM01-02-ZPLSGA010,telemetered,Pending,no parser
Looks good.

2021-05-12 17:08 UTC, snwhite commented on GP02HYPM/GP02HYPM_D00007_ingest.csv
> -#,,GP02HYPM-MPM01-02-ZPLSGA010,telemetered,Pending,no parser
Looks good.

2021-05-12 17:08 UTC, snwhite commented on GS02HYPM/GS02HYPM_D00001_ingest.csv
> -#,,GS02HYPM-MPM01-02-ZPLSGA010,telemetered,Not Deployed,Not deployed
Looks good.

2021-05-12 17:08 UTC, snwhite commented on GS02HYPM/GS02HYPM_D00002_ingest.csv
> -#,,GS02HYPM-MPM01-02-ZPLSGA010,telemetered,Not Deployed,Not deployed
Looks good.

2021-05-12 17:08 UTC, snwhite commented on GS02HYPM/GS02HYPM_D00003_ingest.csv
> -#,,GS02HYPM-MPM01-02-ZPLSGA010,telemetered,Not Expected,No glider deployed so telemetered data will not be available
Looks good.

2021-05-19 20:19 UTC, kuo-james approved these changes

2021-05-20 15:07 UTC, merged

2021-06-02 21:00 UTC, snwhite commented
![](https://github.trello.services/images/mini-trello-icon.png) [Ingestion CSV Review [DT-129]](https://trello.com/c/RERKsbQ4/129-ingestion-csv-review-dt-129)