Irminger 7 Recovered Moorings
oceanobservatories/ingestion-csvs pull request #439
Opened 2021-09-13 19:33 UTC by cdobs

Creates recovered ingestion csvs for Irminger 7:
-GI01SUMO R00007
-GI02HYPM R00007
-GI03FLMA R00007
-GI03FLMB R00007

2021-09-14 23:43 UTC, snwhite approved these changes

2021-09-14 23:43 UTC, snwhite commented on GI01SUMO/GI01SUMO_R00007_ingest.csv
> +mi.dataset.driver.flord_g.ctdbp_p.dcl.flord_g_ctdbp_p_dcl_recovered_driver,/omc_data/whoi/OMC/GI01SUMO/R00007/cg_data/dcl11/imm/ctdbp03/*.DAT,GI01SUMO-RII11-02-FLORDG033,recovered_host,Available,
Should there be lines for FLORD recovered_instr using flord_g_ctdbp_p_recovered_driver?

2021-09-14 23:43 UTC, snwhite commented on GI01SUMO/GI01SUMO_R00007_ingest.csv
> +mi.dataset.driver.fdchp_a.fdchp_a_recovered_driver,/omc_data/whoi/OMC/GI01SUMO/R00007/instruments/dcl12/FDCHP_sn*/D*/fdchp_*.dat,GI01SUMO-SBD12-08-FDCHPA000,recovered_inst,Available,
Looks good.

2021-09-14 23:43 UTC, snwhite commented on GI02HYPM/GI02HYPM_R00007_ingest.csv
> +mi.dataset.driver.vel3d_l.wfp.vel3d_l_wfp_recovered_driver,/omc_data/whoi/OMC/GI02HYPM/R00007/instruments/GWFP_sn*/0*/A*.DA?,GI02HYPM-WFP02-05-VEL3DL000,recovered_wfp,Available,
Looks good.

2021-09-14 23:43 UTC, snwhite commented on GI03FLMA/GI03FLMA_R00007_ingest.csv
> +mi.dataset.driver.flort_dj.sio.flort_dj_sio_recovered_driver,/omc_data/whoi/OMC/GI03FLMA/R00007/cg_data/SSIOC_sn*/FLORT/FLO*.DAT,GI03FLMA-RIS01-05-FLORTD000,recovered_host,Available,
Looks good.

2021-09-14 23:43 UTC, snwhite commented on GI03FLMB/GI03FLMB_R00007_ingest.csv
> +mi.dataset.driver.flort_dj.sio.flort_dj_sio_recovered_driver,/omc_data/whoi/OMC/GI03FLMB/R00007/cg_data/SSIOC_sn*/FLORT/FLO*.DAT,GI03FLMB-RIS01-05-FLORTD000,recovered_host,Available,
Looks good.

2021-09-15 21:07 UTC, rtravis-whoi requested changes
Reviewed by John L and Rebecca - One change needed on SUMO ingest - see comment in file.

2021-09-15 21:07 UTC, rtravis-whoi commented on GI01SUMO/GI01SUMO_R00007_ingest.csv
> +mi.dataset.driver.pco2w_abc.pco2w_abc_recovered_driver,/omc_data/whoi/OMC/GI01SUMO/R00007/instruments/dcl11/imm/PCO2W_snC0104/SAMI*.txt,GI01SUMO-RII11-02-PCO2WC052,recovered_inst,Not Expected,No comm
John & Rebecca - this line should be commented out - no data recovered

2021-09-15 21:37 UTC, rtravis-whoi commented on GI01SUMO/GI01SUMO_R00007_ingest.csv
> +#mi.dataset.driver.pco2w_abc.pco2w_abc_recovered_driver,/omc_data/whoi/OMC/GI01SUMO/R00007/instruments/dcl11/imm/PCO2W_snC0104/SAMI*.txt,GI01SUMO-RII11-02-PCO2WC052,recovered_inst,Not Expected,No com
update looks good - line 55 commented out.

2021-09-15 21:38 UTC, rtravis-whoi approved these changes
correction to GI01SUMO_R00007_ingest.csv looks good (commented out line 55).

2021-09-15 21:39 UTC, rtravis-whoi commented on GI01SUMO/GI01SUMO_R00007_ingest.csv
> +mi.dataset.driver.fdchp_a.fdchp_a_recovered_driver,/omc_data/whoi/OMC/GI01SUMO/R00007/instruments/dcl12/FDCHP_sn*/D*/fdchp_*.dat,GI01SUMO-SBD12-08-FDCHPA000,recovered_inst,Available,
correction to line 55 good.

2021-09-16 12:57 UTC, snwhite approved these changes

2021-09-16 12:57 UTC, snwhite commented on GI01SUMO/GI01SUMO_R00007_ingest.csv
> +#mi.dataset.driver.pco2w_abc.pco2w_abc_recovered_driver,/omc_data/whoi/OMC/GI01SUMO/R00007/instruments/dcl11/imm/PCO2W_snC0104/SAMI*.txt,GI01SUMO-RII11-02-PCO2WC052,recovered_inst,Not Expected,No com
Looks good.

2021-09-23 13:12 UTC, merged