Global surface mooring MET-CT updates
oceanobservatories/ingestion-csvs pull request #544
Opened 2023-11-28 21:28 UTC by cdobs

2023-11-29 14:22 UTC, rtravis-whoi requested changes
Very minor fixes:
GA01SUMO_R00001
line 77 & line 88 - should this be *.hex instead of *hex?

GA01SUMO_R00002
need to add 'Available' at end of line 84

GS01SUMO_R00001
line 77 - recovered_instr line should be commented out

2023-11-29 14:22 UTC, rtravis-whoi commented on GI01SUMO/GI01SUMO_R00003_ingest.csv
> +mi.dataset.driver.metbk_ct.metbk_ct_recovered_driver,/omc_data/whoi/OMC/GI01SUMO/R00003/instruments/dcl12/METBK-CT*/*.hex,GI01SUMO-SBD12-06-METBKA001,recovered_inst,Available,
looks good

2023-11-29 14:22 UTC, rtravis-whoi commented on GI01SUMO/GI01SUMO_R00004_ingest.csv
> +#mi.dataset.driver.metbk_ct.metbk_ct_recovered_driver,/omc_data/whoi/OMC/GI01SUMO/R00004/instruments/dcl12/METBK-CT*/*.hex,GI01SUMO-SBD12-06-METBKA001,recovered_inst,Not Expected,buoy lost: not recov
looks good

2023-11-29 14:22 UTC, rtravis-whoi commented on GI01SUMO/GI01SUMO_R00005_ingest.csv
> +mi.dataset.driver.metbk_ct.metbk_ct_recovered_driver,/omc_data/whoi/OMC/GI01SUMO/R00005/instruments/dcl12/METBK-CT*/*.hex,GI01SUMO-SBD12-06-METBKA001,recovered_inst,Available,
looks good

2023-11-29 14:22 UTC, rtravis-whoi commented on GI01SUMO/GI01SUMO_R00006_ingest.csv
> +mi.dataset.driver.metbk_ct.metbk_ct_recovered_driver,/omc_data/whoi/OMC/GI01SUMO/R00006/instruments/dcl12/METBK-CT*/*.hex,GI01SUMO-SBD12-06-METBKA001,recovered_inst,Available,
looks good

2023-11-29 14:22 UTC, rtravis-whoi commented on GI01SUMO/GI01SUMO_R00007_ingest.csv
> +mi.dataset.driver.metbk_ct.metbk_ct_recovered_driver,/omc_data/whoi/OMC/GI01SUMO/R00007/instruments/dcl12/METBK-CT*/*.hex,GI01SUMO-SBD12-06-METBKA001,recovered_inst,Available,
looks good

2023-11-29 14:22 UTC, rtravis-whoi commented on GI01SUMO/GI01SUMO_R00008_ingest.csv
> +mi.dataset.driver.metbk_ct.metbk_ct_recovered_driver,/omc_data/whoi/OMC/GI01SUMO/R00008/instruments/dcl12/METBK-CT*/*.hex,GI01SUMO-SBD12-06-METBKA001,recovered_inst,Available,
looks good

2023-11-29 14:22 UTC, rtravis-whoi commented on GS01SUMO/GS01SUMO_D00001_ingest.csv
> +mi.dataset.driver.metbk_ct.dcl.metbk_ct_dcl_driver,/omc_data/whoi/OMC/GS01SUMO/D00001/cg_data/dcl12/metbk2/*.metbk*.log,GS01SUMO-SBD12-06-METBKA001,telemetered,Available,
looks good

2023-11-29 14:22 UTC, rtravis-whoi commented on GS01SUMO/GS01SUMO_D00002_ingest.csv
> +mi.dataset.driver.metbk_ct.dcl.metbk_ct_dcl_driver,/omc_data/whoi/OMC/GS01SUMO/D00002/cg_data/dcl12/metbk2/*.metbk*.log,GS01SUMO-SBD12-06-METBKA001,telemetered,Available,
looks good

2023-11-29 14:22 UTC, rtravis-whoi commented on GS01SUMO/GS01SUMO_D00003_ingest.csv
> +mi.dataset.driver.metbk_ct.dcl.metbk_ct_dcl_driver,/omc_data/whoi/OMC/GS01SUMO/D00003/cg_data/dcl12/metbk2/*.metbk2.log,GS01SUMO-SBD12-06-METBKA001,telemetered,Available,
looks good

2023-11-29 14:22 UTC, rtravis-whoi commented on GS01SUMO/GS01SUMO_D00004_ingest.csv
> +mi.dataset.driver.metbk_ct.dcl.metbk_ct_dcl_driver,/omc_data/whoi/OMC/GS01SUMO/D00004/cg_data/dcl12/metbk2/*.metbk2.log,GS01SUMO-SBD12-06-METBKA001,telemetered,Available,
looks good

2023-11-29 14:22 UTC, rtravis-whoi commented on GS01SUMO/GS01SUMO_R00001_ingest.csv
> +mi.dataset.driver.metbk_ct.metbk_ct_recovered_driver,/omc_data/whoi/OMC/GS01SUMO/R00001/cg_data/dcl11/METBK-CT*/*.hex,GS01SUMO-SBD11-06-METBKA001,recovered_inst,Not Available,Data not available
line 77 - recovered_instr line should be commented out

2023-11-29 14:22 UTC, rtravis-whoi commented on GS01SUMO/GS01SUMO_R00002_ingest.csv
> +mi.dataset.driver.metbk_ct.metbk_ct_recovered_driver,/omc_data/whoi/OMC/GS01SUMO/R00002/instruments/dcl12/METBK-CT*/*.hex,GS01SUMO-SBD12-06-METBKA001,recovered_inst,Available,
looks good

2023-11-29 14:22 UTC, rtravis-whoi commented on GS01SUMO/GS01SUMO_R00003_ingest.csv
> +mi.dataset.driver.metbk_ct.metbk_ct_recovered_driver,/omc_data/whoi/OMC/GS01SUMO/R00003/instruments/dcl12/METBK-CT*/*.hex,GS01SUMO-SBD12-06-METBKA001,recovered_inst,Available,
looks good

2023-11-29 14:22 UTC, rtravis-whoi commented on GS01SUMO/GS01SUMO_R00004_ingest.csv
> +mi.dataset.driver.metbk_ct.metbk_ct_recovered_driver,/omc_data/whoi/OMC/GS01SUMO/R00004/instruments/dcl12/METBK-CT*/*.hex,GS01SUMO-SBD12-06-METBKA001,recovered_inst,Available,
looks good

2023-11-29 15:39 UTC, rtravis-whoi approved these changes
updates look good!

2023-12-22 19:12 UTC, cooleyky reviewed
Looks good except for one issue with GI01SUMO/GI01SUMO_R00002_ingest.csv. Asking @cdobs to check this

2023-12-22 19:12 UTC, cooleyky commented on GI01SUMO/GI01SUMO_R00005_ingest.csv
> +mi.dataset.driver.metbk_ct.metbk_ct_recovered_driver,/omc_data/whoi/OMC/GI01SUMO/R00005/instruments/dcl12/METBK-CT*/*.hex,GI01SUMO-SBD12-06-METBKA001,recovered_inst,Available,
looks good

2023-12-22 19:12 UTC, cooleyky commented on GI01SUMO/GI01SUMO_R00006_ingest.csv
> +mi.dataset.driver.metbk_ct.metbk_ct_recovered_driver,/omc_data/whoi/OMC/GI01SUMO/R00006/instruments/dcl12/METBK-CT*/*.hex,GI01SUMO-SBD12-06-METBKA001,recovered_inst,Available,
looks good

2023-12-22 19:12 UTC, cooleyky commented on GI01SUMO/GI01SUMO_R00007_ingest.csv
> +mi.dataset.driver.metbk_ct.metbk_ct_recovered_driver,/omc_data/whoi/OMC/GI01SUMO/R00007/instruments/dcl12/METBK-CT*/*.hex,GI01SUMO-SBD12-06-METBKA001,recovered_inst,Available,
looks good

2023-12-22 19:12 UTC, cooleyky commented on GI01SUMO/GI01SUMO_R00008_ingest.csv
> +mi.dataset.driver.metbk_ct.metbk_ct_recovered_driver,/omc_data/whoi/OMC/GI01SUMO/R00008/instruments/dcl12/METBK-CT*/*.hex,GI01SUMO-SBD12-06-METBKA001,recovered_inst,Available,
looks good

2023-12-22 20:06 UTC, cooleyky approved these changes
Everything looks good after update to GI01SUMO R00002

2023-12-22 20:06 UTC, cooleyky commented on GI01SUMO/GI01SUMO_R00002_ingest.csv
>  mi.dataset.driver.nutnr_b.dcl_full.nutnr_b_dcl_full_recovered_driver,/omc_data/whoi/OMC/GI01SUMO/R00002/cg_data/dcl11/NUTNR_sn274/*.nutnr1.log,GI01SUMO-SBD11-08-NUTNRB000,recovered_host,Available,
update looks good

2023-12-22 20:55 UTC, rtravis-whoi approved these changes
correction to address Kylene's note looks good!

2023-12-22 20:55 UTC, rtravis-whoi commented on GI01SUMO/GI01SUMO_R00002_ingest.csv
>  mi.dataset.driver.nutnr_b.dcl_full.nutnr_b_dcl_full_recovered_driver,/omc_data/whoi/OMC/GI01SUMO/R00002/cg_data/dcl11/NUTNR_sn274/*.nutnr1.log,GI01SUMO-SBD11-08-NUTNRB000,recovered_host,Available,
looks good!

2024-01-23 19:28 UTC, merged