Irminger 9 recovered
oceanobservatories/ingestion-csvs pull request #545
Opened 2023-12-07 18:23 UTC by cdobs

2023-12-11 15:21 UTC, rtravis-whoi commented
Not sure why but I can't submit my comments using the green review button and Approve the PR - tried Friday and this morning.  PR is Approved.

2023-12-12 17:28 UTC, cooleyky requested changes
The CPM file name mask is pointing to an irid2shore directory that doesn't exist yet in the raw data repo. There is a cpm_status.txt file, but it's in the syslog directory instead: https://rawdata-west.oceanobservatories.org/files/GI01SUMO/R00009/cg_data/cpm1/
Everything else in these ingestion CSVs looks good.

2023-12-12 17:28 UTC, cooleyky commented on GI01SUMO/GI01SUMO_R00009_ingest.csv
> +mi.dataset.driver.fdchp_a.fdchp_a_recovered_driver,/omc_data/whoi/OMC/GI01SUMO/R00009/instruments/dcl12/FDCHP_sn*/D*/fdchp_*.dat,GI01SUMO-SBD12-08-FDCHPA000,recovered_inst,Available,
Looks good except for CPM file name mask

2023-12-12 18:47 UTC, cooleyky approved these changes
Looks good after getting confirmation that filename masks are good

2023-12-12 18:47 UTC, cooleyky commented on GI01SUMO/GI01SUMO_R00009_ingest.csv
> +mi.dataset.driver.cg_cpm_eng.cpm.cg_cpm_eng_cpm_recovered_driver,/omc_data/whoi/OMC/GI01SUMO/R00009/cg_data/cpm1/irid2shore/cpm_status*.txt,GI01SUMO-SBC11-00-CPMENG000,recovered_host,Available,
@cdobs confirmed that the directory exists, and this CSV is fine as is

2023-12-12 22:52 UTC, merged