Adds shallow water mooring ingestion csvs
oceanobservatories/ingestion-csvs pull request #558
Opened 2024-04-12 18:44 UTC by cdobs

2024-04-12 19:49 UTC, reedan88 requested changes
Some of the reference designators have quotation marks and white space that should probably be removed (even if they aren't active)

2024-04-12 19:49 UTC, reedan88 commented on CP11SOSM/CP11SOSM_D00001_ingest.csv
Looks good.

2024-04-12 19:49 UTC, reedan88 commented on CP12CNSW/CP12CNSW_D00001_ingest.csv
> +#,,"CP12CNSW-MFI01-02-CTDMOS031	",telemetered,Not Expected,No telem data; not hooked up inductively for this deployment
I think you pasted in some extra quotation marks

2024-04-12 19:49 UTC, reedan88 commented on CP12CNSW/CP12CNSW_D00001_ingest.csv
> +mi.dataset.driver.cg_stc_eng.stc.mopak_o_dcl_telemetered_driver,/omc_data/whoi/OMC/CP12CNSW/D00001/3dmgx3/*3dmgx3.log,"CP12CNSW-SBS01-05-MOPAK0000	",telemetered,Available,
Have quotation marks and white space in the reference designator

2024-04-12 19:49 UTC, reedan88 commented on CP12WESW/CP12WESW_D00001_ingest.csv
> +#,,"CP12WESW-MFI01-02-CTDMOS031	",telemetered,Not Expected,No telem data; not hooked up inductively for this deployment
Extra quotation marks around the reference designator

2024-04-12 19:49 UTC, reedan88 commented on CP12WESW/CP12WESW_D00001_ingest.csv
> +mi.dataset.driver.cg_stc_eng.stc.mopak_o_dcl_telemetered_driver,/omc_data/whoi/OMC/CP12WESW/D00001/3dmgx3/*3dmgx3.log,"CP12WESW-SBS01-05-MOPAK0000	",telemetered,Available,
Extra quotation marks and white space in the reference designator

2024-04-12 19:57 UTC, reedan88 approved these changes

2024-04-12 19:57 UTC, reedan88 commented on CP12CNSW/CP12CNSW_D00001_ingest.csv
Looks good.

2024-04-12 19:57 UTC, reedan88 commented on CP11SOSM/CP11SOSM_D00001_ingest.csv
Looks good.

2024-04-12 19:57 UTC, reedan88 commented on CP12WESW/CP12WESW_D00001_ingest.csv
Looks good.

2024-04-15 14:43 UTC, snwhite approved these changes

2024-04-15 14:43 UTC, snwhite commented on CP11SOSM/CP11SOSM_D00001_ingest.csv
> +#mi.dataset.driver.optaa_dj.dcl.optaa_dj_dcl_telemetered_driver,/omc_data/whoi/OMC/CP11SOSM/D00001/cg_data/dcl37/optaa2_decimated/*.optaa2.log,CP11SOSM-MFD37-01-OPTAAD000,telemetered,Not Expected,Fai
Looks good.

2024-04-15 14:43 UTC, snwhite commented on CP12WESW/CP12WESW_D00001_ingest.csv
> +#,/omc_data/whoi/OMC/CP12WESW/D00001/imm/prkt/*.DAT,CP12WESW-WFP01-03-FLORTP000,telemetered,Expected,Parser tbd
Looks fine.  Like 4 has an extra space after the #.

2024-04-15 14:43 UTC, snwhite commented on CP12CNSW/CP12CNSW_D00001_ingest.csv
> +#,/omc_data/whoi/OMC/CP12CNSW/D00001/imm/prkt/*.DAT,CP12CNSW-WFP01-03-FLORTP000,telemetered,Expected,Parser tbd
Looks fine.  Like 4 has an extra space after the #.

2024-04-15 20:08 UTC, merged