Irminger 10 recovered ingestion csvs
oceanobservatories/ingestion-csvs pull request #575
Opened 2024-07-19 17:47 UTC by cdobs

2024-07-19 20:51 UTC, rtravis-whoi requested changes
on FLMB CTDMOG068 - checklist & raw data repo show recovered instrument data - I think this being commented out w 'not available/no recovered data' is a copy/paste error from R00009.

2024-07-19 20:51 UTC, rtravis-whoi commented on GI01SUMO/GI01SUMO_R00010_ingest.csv
> +mi.dataset.driver.fdchp_a.fdchp_a_recovered_driver,/omc_data/whoi/OMC/GI01SUMO/R00010/instruments/dcl12/FDCHP_sn*/D*/fdchp_*.dat,GI01SUMO-SBD12-08-FDCHPA000,recovered_inst,Available,
looks good

2024-07-19 20:51 UTC, rtravis-whoi commented on GI02HYPM/GI02HYPM_R00010_ingest.csv
> +mi.dataset.driver.vel3d_l.wfp.vel3d_l_wfp_recovered_driver,/omc_data/whoi/OMC/GI02HYPM/R00010/instruments/GWFP_sn*/0*/A*.DA?,GI02HYPM-WFP02-05-VEL3DL000,recovered_wfp,Available,
looks good

2024-07-19 20:51 UTC, rtravis-whoi commented on GI03FLMA/GI03FLMA_R00010_ingest.csv
> +mi.dataset.driver.flort_dj.sio.flort_dj_sio_recovered_driver,/omc_data/whoi/OMC/GI03FLMA/R00010/cg_data/SSIOC_sn*/FLORT/FLO*.DAT,GI03FLMA-RIS01-05-FLORTD000,recovered_host,Available,
looks good

2024-07-19 20:51 UTC, rtravis-whoi commented on GI03FLMB/GI03FLMB_R00010_ingest.csv
> +#mi.dataset.driver.ctdmo_ghqr.sio.ctdmo_ghqr_ct_recovered_driver,/omc_data/whoi/OMC/GI03FLMB/R00010/instruments/CTDMO_sn37-13623/*.hex,GI03FLMB-RIM01-02-CTDMOG068,recovered_inst,Not Available,No reco
checklist & raw data repo show recovered instrument data - I think this being commented out w 'not available/no recovered data' is a copy/paste error from R00009.

2024-07-19 20:58 UTC, rtravis-whoi approved these changes

2024-07-19 20:58 UTC, rtravis-whoi commented on GI03FLMB/GI03FLMB_R00010_ingest.csv
> +mi.dataset.driver.flort_dj.sio.flort_dj_sio_recovered_driver,/omc_data/whoi/OMC/GI03FLMB/R00010/cg_data/SSIOC_sn*/FLORT/FLO*.DAT,GI03FLMB-RIS01-05-FLORTD000,recovered_host,Available,
correction to CTDMOG068 recovered_instr looks good

2024-07-22 18:14 UTC, cooleyky commented on GI01SUMO/GI01SUMO_R00010_ingest.csv
> +mi.dataset.driver.fdchp_a.fdchp_a_recovered_driver,/omc_data/whoi/OMC/GI01SUMO/R00010/instruments/dcl12/FDCHP_sn*/D*/fdchp_*.dat,GI01SUMO-SBD12-08-FDCHPA000,recovered_inst,Available,
looks good

2024-07-23 16:28 UTC, merged